spring.application.name=fairteam-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fairteam_db
spring.datasource.username=postgres
spring.datasource.password=sadi.c1244.del

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080